name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Iterative Setup
        uses: iterative/setup-cml@v1
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          #pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          #add figure to the report
          echo "## validating results by region"
          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md
